accounts/urls.py
from django.urls import path
from accounts.views import AccountDetailView
from accounts.api.views import AccountAPIView, AccountDetailAPIView
from accounts.api.views_v2 import AccountRetrieveAPI, AccountListAPI, AccountCreateAPI, AccountUpdateAPI, \
    AccountDeleteAPI
from accounts.api.views_v3 import AccountListCreateAPI, AccountRetrieveUpdateDestroyAPI

app_name = 'accounts'

urlpatterns = [
    path('details/<int:pk>/', AccountDetailView.as_view(), name='details'),

    path('api/v1', AccountAPIView.as_view()),
    path('api/v1/<int:pk>', AccountDetailAPIView.as_view()),
    path('api/v2', AccountListAPI.as_view()),
    path('api/v2/create', AccountCreateAPI.as_view()),
    path('api/v2/retrieve/<int:pk>', AccountRetrieveAPI.as_view()),
    path('api/v2/update/<int:pk>', AccountUpdateAPI.as_view()),
    path('api/v2/delete/<int:pk>', AccountDeleteAPI.as_view()),
    path('api/v3', AccountListCreateAPI.as_view()),
    path('api/v3/<int:pk>', AccountRetrieveUpdateDestroyAPI.as_view()),

]

banks/urls.py
from django.urls import path
from banks.api.views import BankAPIView, BankDetailAPIView
from banks.api.views_v2 import BankRetrieveAPI, BankListAPI, BankCreateAPI, BankUpdateAPI, BankDeleteAPI
from banks.api.views_v3 import BankListCreateAPI, BankRetrieveUpdateDestroyAPI
from banks.api.views import BranchAPIView, BranchDetailAPIView
from banks.api.views_v2 import BranchRetrieveAPI, BranchListAPI, BranchCreateAPI, BranchUpdateAPI, BranchDeleteAPI
from banks.api.views_v3 import BranchListCreateAPI, BranchRetrieveUpdateDestroyAPI

app_name = 'banks'

urlpatterns = [

    path('api/v1', BankAPIView.as_view()),
    path('api/v1/<int:pk>', BankDetailAPIView.as_view()),
    path('api/v2', BankListAPI.as_view()),
    path('api/v2/create', BankCreateAPI.as_view()),
    path('api/v2/retrieve/<int:pk>', BankRetrieveAPI.as_view()),
    path('api/v2/update/<int:pk>', BankUpdateAPI.as_view()),
    path('api/v2/delete/<int:pk>', BankDeleteAPI.as_view()),
    path('api/v3', BankListCreateAPI.as_view(), name="bank-list"),
    path('api/v3/<int:pk>', BankRetrieveUpdateDestroyAPI.as_view(), name="bank"),

    path('branch/api/v1', BranchAPIView.as_view()),
    path('branch/api/v1/<int:pk>', BranchDetailAPIView.as_view()),
    path('branch/api/v2', BranchListAPI.as_view()),
    path('branch/api/v2/create', BranchCreateAPI.as_view()),
    path('branch/api/v2/retrieve/<int:pk>', BranchRetrieveAPI.as_view()),
    path('branch/api/v2/update/<int:pk>', BranchUpdateAPI.as_view()),
    path('branch/api/v2/delete/<int:pk>', BranchDeleteAPI.as_view()),
    path('branch/api/v3', BranchListCreateAPI.as_view()),
    path('branch/api/v3/<int:pk>', BranchRetrieveUpdateDestroyAPI.as_view()),

]

transaction_management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import HomeView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('accounts.urls')),
    path('transactions/', include('transactions.urls')),
    path('banks/', include('banks.urls')),

]

transactions/urls.py
from django.urls import path
from .views import TransactionListView
from transactions.api.views import TransactionAPIView, TransactionDetailAPIView
from transactions.api.views_v2 import TransactionRetrieveAPI, TransactionListAPI, TransactionCreateAPI, \
    TransactionUpdateAPI, TransactionDeleteAPI
from transactions.api.views_v3 import TransactionListCreateAPI, TransactionRetrieveUpdateDestroyAPI

app_name = 'transactions'

urlpatterns = [
    path('', TransactionListView.as_view(), name="transaction"),

    path('api/v1', TransactionAPIView.as_view()),
    path('api/v1/<int:pk>', TransactionDetailAPIView.as_view()),
    path('api/v2', TransactionListAPI.as_view()),
    path('api/v2/create', TransactionCreateAPI.as_view()),
    path('api/v2/retrieve/<int:pk>', TransactionRetrieveAPI.as_view()),
    path('api/v2/update/<int:pk>', TransactionUpdateAPI.as_view()),
    path('api/v2/delete/<int:pk>', TransactionDeleteAPI.as_view()),
    path('api/v3', TransactionListCreateAPI.as_view()),
    path('api/v3/<int:pk>', TransactionRetrieveUpdateDestroyAPI.as_view()),

]

core/models.py
from django.db import models
from django.contrib.auth import get_user_model


user = get_user_model()


class AuditFieldMixin(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(user, verbose_name="created by", on_delete=models.PROTECT,
                                   related_name="created_%(app_label)s_%(class)s_set")
    modified = models.DateTimeField(auto_now=True)
    modified_by = models.ForeignKey(user, verbose_name="modified by", on_delete=models.PROTECT,
                                    related_name="modified_%(app_label)s_%(class)s_set")

    class Meta:
        abstract = True


class SoftDeleteMixin(models.Model):
    is_active = models.BooleanField(default=True)

    class Meta:
        abstract = True

core/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'core/index.html'

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="Dummy Transaction System" />
        <meta name="author" content="Muhammad Hamza" />
        <title>
            {% block head_title %}Transaction Management System{% endblock %}
        </title>
        <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">

        {% block head_extra %}{% endblock %}
    </head>
    <body class="bg-gray-100">
        {% block body %}
            {% include 'core/navbar.html' %}
            <div class="lg:container lg:mx-auto">
                {% include 'core/messages.html' %}
                {% block content %}
                <!-- Add content here -->
                {% endblock %}
            </div>
        {% endblock %}
        {% block footer_extra %}{% endblock %}
    </body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block head_title %}Transaction Management System{% endblock %}

{% block content %}
    <div class="container mx-auto flex flex-col md:flex-row items-center my-12 md:my-24">
        <!--Left Col-->
        <div class="flex flex-col w-full lg:w-1/2 justify-center items-start pt-12 pb-24 px-6">
            <h1 class="font-bold text-4xl my-4">Transaction Management System</h1>
            <p class="leading-normal mb-4">
            </p>
        </div>

    </div>
{% endblock %}

core/templates/core/messages.html
{% for message in messages %}
    <div class="bg-teal-100 border-t-4 border-teal-500 rounded-b text-teal-900 px-4 py-3 shadow-md mt-2" role="alert">
        <div class="flex">
            <div class="py-1">
                <svg class="fill-current h-6 w-6 text-teal-500 mr-4" xmlns="http://www.w3.org/2000/svg"
                     viewBox="0 0 20 20">
                    <path d="M2.93 17.07A10 10 0 1 1 17.07 2.93 10 10 0 0 1 2.93 17.07zm12.73-1.41A8 8 0 1 0 4.34 4.34a8 8 0 0 0 11.32 11.32zM9 11V9h2v6H9v-4zm0-6h2v2H9V5z"/>
                </svg>
            </div>
            <div>
                <p class="font-bold">Success!</p>
                <p class="text-sm">{{ message }}</p>
            </div>
        </div>
    </div>
{% endfor %}

core/templates/core/navbar.html
<nav class="flex items-center justify-between flex-wrap bg-gray-800 p-6">
    <div class="flex items-center flex-shrink-0 text-white mr-6">
        <span class="font-semibold text-xl tracking-tight">Transaction Management System</span>
    </div>
    <div class="block lg:hidden">
        <button class="flex items-center px-3 py-2 border rounded text-white border-white-400 hover:text-white hover:border-white">
            <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title>
                <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/>
            </svg>
        </button>
    </div>
    <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
        {% if request.user.is_authenticated %}
            <div class="text-md lg:flex-grow">
                <a href="{% url 'accounts:details' pk=request.user.id %}"
                   class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                    Account Details
                </a>
                <a href="{% url 'transactions:transaction' %}"
                   class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                    Transaction Report
                </a>
                <a href="" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                    Withdraw
                </a>
                <a href="" class="block mt-4 lg:inline-block lg:mt-0 text-white hover:text-white mr-4">
                    Deposit
                </a>
            </div>
            <div>
                {% comment %} <a href="{% url 'accounts:user_logout' %}" class="inline-block font-medium text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-gray-800 hover:bg-white mt-4 lg:mt-0">Logout</a> {% endcomment %}
            </div>
        {% else %}
            <div class="text-md lg:flex-grow"></div>
            <div>
                <a href="/admin/"
                   class="mr-2 inline-block font-medium text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-gray-800 hover:bg-white mt-4 lg:mt-0">Login</a>
            </div>
            <div>
                {% comment %} <a href="{% url 'accounts:user_registration' %}" class="inline-block font-medium text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-gray-800 hover:bg-white mt-4 lg:mt-0">Register</a> {% endcomment %}
            </div>
        {% endif %}
    </div>
</nav>